name: 中青看看赚

on:
  workflow_dispatch:
  schedule:
     - cron: '3 0 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行【中青看看赚】'     
        run: |
          node youth_gain.js
        env:
          YOUTH_START: ${{ secrets.YOUTH_START }}
          YOUTH_LOOK: ${{ secrets.YOUTH_LOOK }}
